const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('electronAPI', {
  openDirectory: () => ipcRenderer.invoke('dialog:openDirectory'),
  scanDirectory: (dirPath) => ipcRenderer.invoke('scan-directory', dirPath),
  scanSpecificFiles: (arr) => ipcRenderer.invoke('scan-specific-files', arr),
  getEverythingSize: (dirPath) => ipcRenderer.invoke('get-everything-size', dirPath),
  getTrickplaySprites: (folder) => ipcRenderer.invoke('get-trickplay-sprites', folder),
  getFileSize: (p) => ipcRenderer.invoke('get-file-size', p),
  openFile: (filePath) => ipcRenderer.invoke('open-file', filePath),
  showInFolder: (filePath) => ipcRenderer.invoke('show-in-folder', filePath),
  copyToClipboard: (text) => ipcRenderer.invoke('copy-to-clipboard', text),
  showContextMenu: (item) => ipcRenderer.invoke('show-context-menu', item),
  generateWebm: (p, vaultRoot) => ipcRenderer.invoke('generate-webm', p, vaultRoot),
  upscaleVideo: (p) => ipcRenderer.invoke('upscale-video', p),
  renameFile: (oldPath, newName) => ipcRenderer.invoke('rename-file', oldPath, newName),
  deleteItem: (p) => ipcRenderer.invoke('delete-item', p),
  getFolderSizeBackground: (dirPath) => ipcRenderer.invoke('get-folder-size-background', dirPath),
  getSettings: () => ipcRenderer.invoke('get-settings'),
  saveSettings: (s) => ipcRenderer.invoke('save-settings', s),
  getTheme: () => ipcRenderer.invoke('get-theme'),
  setTheme: (t) => ipcRenderer.invoke('set-theme', t),
  scheduleIdlePreviews: (items) => ipcRenderer.invoke('schedule-idle-previews', items),
  pasteFiles: (data) => ipcRenderer.invoke('paste-files', data),
  zipSelection: (data) => ipcRenderer.invoke('zip-selection', data),
  getFileProperties: (p) => ipcRenderer.invoke('get-file-properties', p),
  getFolderSizeSmart: (dirPath, fileCount) => ipcRenderer.invoke('get-folder-size-smart', dirPath, fileCount),
  encryptFiles: (data) => ipcRenderer.invoke('encrypt-files', data),
  decryptFiles: (data) => ipcRenderer.invoke('decrypt-files', data),
  startUpscaleStream: (data) => ipcRenderer.invoke('upscale-stream-start', data),
  stopUpscaleStream: () => ipcRenderer.invoke('upscale-stream-stop'),
  onUpscaleChunk: (cb) => ipcRenderer.on('upscale-chunk', (_, data) => cb(data)),
  offUpscaleChunk: () => ipcRenderer.removeAllListeners('upscale-chunk'),
  onUpscaleStatus: (cb) => ipcRenderer.on('upscale-status', (_, data) => cb(data)),
  offUpscaleStatus: () => ipcRenderer.removeAllListeners('upscale-status'),
  findSubtitles: (videoPath) => ipcRenderer.invoke('find-subtitles', videoPath),
  onWebmProgress: (cb) => ipcRenderer.on('generate-webm-progress', (_, data) => cb(data)),
  offWebmProgress: () => ipcRenderer.removeAllListeners('generate-webm-progress'),
  normalizeAudio: (videoPath, vaultRoot, transcribe, translateTo) => ipcRenderer.invoke('normalize-audio', { videoPath, vaultRoot, transcribe, translateTo }),
  onNormalizeProgress: (cb) => ipcRenderer.on('normalize-progress', (_, data) => cb(data)),
  offNormalizeProgress: () => ipcRenderer.removeAllListeners('normalize-progress'),
  onUpscaleProgress: (cb) => ipcRenderer.on('upscale-progress', (_, data) => cb(data)),
  offUpscaleProgress: () => ipcRenderer.removeAllListeners('upscale-progress'),
  runASRBenchmark: (forceSimulation) => ipcRenderer.invoke('run-asr-benchmark', { forceSimulation }),
  revertEnhancements: (p) => ipcRenderer.invoke('revert-enhancements', p),
  searchTMDB: (query) => ipcRenderer.invoke('search-tmdb', query),
  searchTorrents: (movieTitle) => ipcRenderer.invoke('search-torrents', movieTitle),
  streamRDTorrent: (data) => ipcRenderer.invoke('rd-stream-torrent', data),
  debridURL: (data) => ipcRenderer.invoke('rd-unrestrict-url', data),
  downloadDebridFile: (data) => ipcRenderer.invoke('rd-download-file', data),
  testDebridProxy: (proxy) => ipcRenderer.invoke('rd-test-proxy', proxy),
  onDownloadProgress: (cb) => ipcRenderer.on('rd-download-progress', (_, data) => cb(data)),
  offDownloadProgress: () => ipcRenderer.removeAllListeners('rd-download-progress')
});
